version: "3.3"

services:

  spring:
    build:
      context: "./spring"
      dockerfile: "Dockerfile"
    restart: on-failure
    ports:
      - 8089:8089
    stdin_open: true
    tty: true

  angular:
    build:
      context: "./YanportFront"
      dockerfile: "Dockerfile"
    ports:
      - 4200:4200
